<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>									
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="<?= BASE_URL; ?>alumno/grabar" name="form" id="form" novalidate="novalidate">
                    <div class="control-group">
                        <label class="control-label">Sección</label>
                        <div class="controls">
                        <select name="nivel" id="id_nivel">
                        <option value=""> ---NIVEL--- </option>
                        <?php foreach ($this->niveles as $nivel): ?>
                        <option value="<?php echo $nivel->nivel; ?>"> <?php echo $nivel->nomnivel; ?> </option>                        
                        <?php endforeach; ?>
                        </select>
                        <select name="grado" id="id_grado">
                        <option value=""> ---GRADO--- </option>
                        <?php foreach ($this->grados as $grado): ?>
                        <option value="<?php echo $grado->codigo; ?>"> <?php echo $grado->grado; ?> </option>                        
                        <?php endforeach; ?>
                        </select>
                        <select name="cod_seccion" id="id_cod_seccion">
                            <option value=""> ---SECCION--- </option>
                        </select>                        
                        </div>
                    </div>
                    <!-- 
	paterno=apaterno,
	materno=amaterno,
	nombres=anombres,
	nacionalidad=anacionalidad,
	sexo=asexo,
	dni=adni,
	fechainscripcion=afechainscripcion,
	matriculante=amatriculante,
	fechanacimiento=afechanacimiento,
	departamento_nac=adepartamento_nac,
	provincia_nac=provincia_nac,
	distrito_nac=adistrito_nac,
	localidad_nac=alocalidad_nac,
	tipodeparto=atipodeparto,
	descripcion_parto=adescripcion_parto,
	departamento=adepartamento,
	provincia=aprovincia,
	distrito=adistrito,
	domicilio=adomicilio,
	ano_residencia=aano_residencia,
	celular=acelular,
	fijo=afijo,
	rpm=arpm,
	rpc=arpc,
	email=aemail,
	religion=areligion,
	alergicomedicamento1=aalergicomedicamento1,
	alergicomedicamento2=aalergicomedicamento2,
	alergicomedicamento3=aalergicomedicamento3,
	alergicomedicamento4=aalergicomedicamento4,
	alergia_polvo_acaro=aalergia_polvo_acaro,
	alergia_humedad_hongos=aalergia_humedad_hongos,
	tipo_sangre=atipo_sangre,
	becado=abecado,
	tipo_beca=atipo_beca,
	resolucion_beca=aresolucion_beca,
	cant_hermanos=acant_hermanos,
	lugar_hermanos=alugar_hermanos,
	colegioprocedente=acolegioprocedente
	where codigo=acodigo; -->
                    <div class="form-actions">
                        <input type="submit" value="Grabar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>