<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>									
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="<?= BASE_URL; ?>alumno/grabar" name="form" id="form" novalidate="novalidate">
                    <div class="control-group">
                        <label class="control-label">Sección</label>
                        <div class="controls">
                        <select name="nivel" id="id_nivel">
                        <option value=""> ---NIVEL--- </option>
                        <?php foreach ($this->niveles as $nivel): ?>
                        <option value="<?php echo $nivel->nivel; ?>"> <?php echo $nivel->nomnivel; ?> </option>                        
                        <?php endforeach; ?>
                        </select>
                        <select name="grado" id="id_grado">
                        <option value=""> ---GRADO--- </option>
                        <?php foreach ($this->grados as $grado): ?>
                        <option value="<?php echo $grado->codigo; ?>"> <?php echo $grado->grado; ?> </option>                        
                        <?php endforeach; ?>
                        </select>                       
                        </div>
                    <div class="row-fluid">
                        <div class="span2">
                        <?php echo $this->form->acod_seccion; ?>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span3">
                        <?php echo $this->form->apaterno; ?>
                        </div>
                        <div class="span3">
                        <?php echo $this->form->amaterno; ?>
                        </div>
                        <div class="span3">
                        <?php echo $this->form->anombres; ?>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span3">
                        <?php echo $this->form->anacionalidad; ?>
                        </div>
                        <div class="span3">
                        <?php echo $this->form->asexo; ?>
                        </div>
                        <div class="span3">
                        <?php echo $this->form->adni; ?>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span3">
                        <?php echo $this->form->afechainscripcion; ?>
                        </div>
                        <div class="span3">
                        <?php echo $this->form->amatriculante; ?>
                        </div>
                        <div class="span3">
                        <?php echo $this->form->afechanacimiento; ?>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span3">
                        <?php echo $this->form->adepartamento_nac; ?>
                        </div>
                        <div class="span3">
                        <?php echo $this->form->aprovincia_nac; ?>
                        </div>
                        <div class="span3">
                        <?php echo $this->form->adistrito_nac; ?>
                        </div>
                    </div>
                        
                    </div>
                    <div class="form-actions">
                        <input type="submit" value="Grabar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>