<!--    <h1><?= isset($this->titulo)?$this->titulo:''; ?></h1>
    <div class="btn-group">
            <a class="btn btn-large tip-bottom" title="Agregar docente"><i class="icon-user"></i></a>
    </div>-->
</div>

<div class="row-fluid">
    <div class="span12">
        <? if(isset($this->mensaje)): ?>
        <div class="alert alert-<?= $this->mensaje['tipo']; ?>"><?= $this->mensaje['texto']; ?><a href="#" class="close" data-dismiss="alert">×</a></div>
        <? endif; ?>
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-hover table-bordered table-striped data-table dataTable">
                    <thead>
                        <tr>
                            <th>CODIGO</th>
                            <th>SECCION</th>
                            <th>ASIGNATURA</th>
                            <th>I</th><th>II</th><th>III</th><th>IV</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->busregbydoc as $registrodocente): ?>
                        <tr>
                            <td><?=$registrodocente->codigo;?></td>
                            <td><?='<b>'.$registrodocente->grado.''.$registrodocente->nombreseccion.'</b> DE '.$registrodocente->nomnivel;?></td>
                            <td><?=$registrodocente->asinatura;?></td>
                            <td><?=$registrodocente->I;?></td>
                            <td><?=$registrodocente->II;?></td>
                            <td><?=$registrodocente->III;?></td>
                            <td><?=$registrodocente->IV;?></td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>