<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="icon-align-justify"></i></span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">

<?php 
foreach ($this->datosindicador as $dateind):

endforeach; ?>
<center>
    <form class="form-horizontal" method="post" action="<?= BASE_URL; ?>indicador/procedure" name="form" id="form" novalidate="novalidate">

<div class="control-group" style="display: none;">
    <div class="controls">
        <input type='text' id='txtcode' name='txtcode' value="<?=$dateind->codigo;?>">
    </div>
</div>
    
<div class="control-group" style="display: none;">
    <div class="controls">
        <input type='text' id='txtcomponente' name='txtcomponente' value="<?=$dateind->idcomponente;?>">
    </div>
</div>
    
<div class="control-group" style="display: none;">
    <div class="controls">
        <input id="txtfiu" name="txtfiu" type="text" value="<?=$dateind->nro_criterio;?>"/>
    </div>
</div>
    
<div class="control-group" style="display: none;">
    <div class="controls">
        <input type='text' id='txtpeso' name='txtpeso' value="<?=$dateind->peso;?>"/>
    </div>
</div>

<div class="control-group">
    <label class="control-label">CRITERIO:  </label>
    <div class="controls">
        <input type='text' id='txtcriterio' name='txtcriterio' style='width: 95%' value="<?=$dateind->criterio;?>"/>
    </div>
</div>

<div class="control-group" style="display: none;">
    <div class="controls">
        <input type='text' id='txtbimestre' name='txtbimestre'  value="<?=$this->bim;?>"/>
    </div>
</div>
        
<div class="control-group" style="display: none;">
    <div class="controls">
        <input type='text' id='txtsina' name='txtsina'  value="<?=$this->sinatures;?>"/>
    </div>
</div>
        
<div class="control-group">
    <div class="controls">
        <button type="submit" id='enviar' class="btn btn-primary btn-sm">Enviar</button>
          <button type="reset" class="btn btn-primary pull-center" >Borrar</button>
          <button type="button" class="btn btn-primary btn-sm" id="buttncan" name="buttncan" onclick="window.location.href='<?= BASE_URL; ?>indicador/criterio/<?=$this->sinatures;?>/<?=$this->bim;?>'">Cancelar</button>
    </div>
</div>
</form>
</center>

            <div class="pagination">
                <ul><!-- AQUI EL CODIGO DE PAGINACION--></ul>
            </div>
<?='Bimestre Actual: '.BIM_ACTUAL;?>
            </div>
        </div>
    </div>
</div>