    <h1><?= isset($this->titulo)?$this->titulo:''; ?></h1>
    <div class="btn-group">
            <a class="btn btn-large tip-bottom" title="Manage Files"><i class="icon-file"></i></a>
            <a class="btn btn-large tip-bottom" title="Manage Users"><i class="icon-user"></i></a>
            <a class="btn btn-large tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">25</span></a>
    </div>
</div>

<div id="container-fluid">
<div class="row-fluid">
    <div class="span12">
        <center><div class="widget-box"  style="width: 65%;">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">
            <table class="table table-bordered table-striped">
                <thead><tr><th>GRADO</th><th>VER</th></tr></thead>
                <tbody>
                <tr>
                    <td><center>3° A&Ntilde;OS</center></td><td><a href="<?= BASE_URL; ?>indicador/sinaturas/inicial/3"><strong>VER &Aacute;REAS</strong></a></td>
                </tr>
                <tr>
                    <td><center>4° A&Ntilde;OS</center></td><td><a href="<?= BASE_URL; ?>indicador/sinaturas/inicial/4"><strong>VER &Aacute;REAS</strong></a></td>
                </tr>
                <tr>
                    <td><center>5° A&Ntilde;OS</center></td><td><a href="<?= BASE_URL; ?>indicador/sinaturas/inicial/5"><strong>VER &Aacute;REAS</strong></a></td>
                </tr>
                </tbody>
            </table>
            </div>
        </div></center>
    </div>
</div>
