<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">


<table class="table table-hover">
<?php foreach ($this->componente as $componente) {?>
    <tr>
        <td style='width:10%'><h4><?=$componente->nrocomponent;?></h4></td>
        <td style='width:90%'><h4><?=$componente->componente;?></h4></td>
    </tr>
    <tr>
        <td colspan=2>
            <a href='<?= BASE_URL; ?>indicador/add/<?=$componente->codigo;?>' TARGET = '_blank' title='Agrega un nuevo indicador'><i>AGREGAR UN NUEVO INDICADOR</i></a>
        </td>
    </tr>
    <tr>
        
    </tr>
<?php }

//echo "
//<tr class='success'>
//    <td style='width:10%'><h4> $row[1] </h4></td>
//    <td><h4> $namecom </h4></td>
//</tr>";
//echo "
//<tr>
//    <td colspan=2>
//    <a href='regindicador.php?componente=".$row[0]."' TARGET = '_blank' title='Agrega un nuevo indicador'><i>AGREGAR UN NUEVO INDICADOR</i>
//        <i class='icon icon-plus'></i><a onclick='Indcompo($row[0],1);'>Ver Indicadores</a>
//    </a>
//    </td>
//</tr>";
//
//$lista=$INDICAXD->LISTAR($row[0]);
//while ($row2 = mysql_fetch_array($lista)) {
//    echo "
//<tr>
//    <td>
//    <a href='regindicador.php?componente= $row[0] &orden= $row2[3] &indicador=$row2[2] &codeindi= $row2[0]' TARGET = '_blank' title='Edita el indicador'>
//    $row[1] $row2[3]
//    <i class='icon icon-edit'></i>
//    </a>
//    </td>
//    <td>".$row2[2]."</td>
//</tr>";
//}
//
//
//
//echo $arraya[3]."leo";
//
?>
</table>

                <div class="pagination">
                    <ul>
                        <!-- AQUI EL CODIGO DE PAGINACION-->
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>