<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">


<table class="table table-hover">
<?php foreach ($this->componente as $componente): ?>
    <tr>
        <td style='width:10%'><h4><?=$componente->nrocomponent;?></h4></td>
        <td style='width:90%'><h4><?=$componente->componente;?></h4></td>
    </tr>
    <tr>
        <td colspan="2"><a href='<?= BASE_URL; ?>indicador/add/<?=$componente->codigo;?>/<?=$this->bimestre;?>/<?=$this->sinatures;?>' title='Agrega un nuevo indicador'><i>AGREGAR UN NUEVO INDICADOR</i></a></td>
    </tr>    
    <tr>
<?php $indicadores = $this->serviceindicador->listbycomponent($componente->codigo); ?>
    <?php foreach ($indicadores as $indicador): ?>
    <tr>
        <td><a href='<?= BASE_URL; ?>indicador/editar/<?=$indicador->codigo;?>/<?=$this->bimestre;?>/<?=$this->sinatures;?>'><?='<b>'.$componente->nrocomponent.'</b>.'.$indicador->nro_criterio;?></a></td>
        <td><?=$indicador->criterio;?></td>
    </tr>
    <?php endforeach; ?>
    </tr>
    <tr>
        
    </tr>
<?php endforeach;?>
</table>

                <div class="pagination">
                    <ul>
                        <!-- AQUI EL CODIGO DE PAGINACION-->
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>