<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">

<table class="table table-hover">
    <thead>
        <tr><th>GRADO</th><th><center>VER</center></th></tr>
    </thead>
    <tbody>
        <tr>
            <td><center>1° GRADO</center></td><td><a href="<?= BASE_URL; ?>indicador/sinaturas/secundaria/1"><strong>VER &Aacute;REAS</strong></a></td>
        </tr>
        <tr>
            <td><center>2° GRADO</center></td><td><a href="<?= BASE_URL; ?>indicador/sinaturas/secundaria/2"><strong>VER &Aacute;REAS</strong></a></td>
        </tr>
        <tr>
            <td><center>3° GRADO</center></td><td><a href="<?= BASE_URL; ?>indicador/sinaturas/secundaria/3"><strong>VER &Aacute;REAS</strong></a></td>
        </tr>
        <tr>
            <td><center>4° GRADO</center></td><td><a href="<?= BASE_URL; ?>indicador/sinaturas/secundaria/4"><strong>VER &Aacute;REAS</strong></a></td>
        </tr>
        <tr>
            <td><center>5° GRADO</center></td><td><a href="<?= BASE_URL; ?>indicador/sinaturas/secundaria/5"><strong>VER &Aacute;REAS</strong></a></td>
        </tr>
    </tbody>
</table>

            </div>
        </div>
    </div>
</div>