<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered table-striped data-table dataTable">
                    <thead>
                        <tr>
                            <th>Ver</th>
                            <th>Asignatura</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- AQUI EL WHILE -->
                        <?php foreach($this->areas as $area): ?>
                        <tr>
                            <td><?php echo $area->codigo;?></td>
                            <td><?php echo $area->asinatura;?></td>
                            
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>


                <div class="pagination">
                    <ul>
                        <!-- AQUI EL CODIGO DE PAGINACION-->
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>