<div class="row-fluid">
    <div class="span12">
        <? if(isset($this->mensaje)): ?>
        <div class="alert alert-<?= $this->mensaje['tipo']; ?>"><?= $this->mensaje['texto']; ?><a href="#" class="close" data-dismiss="alert">×</a></div>
        <? endif; ?>
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>									
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered table-striped data-table dataTable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>					
                        <!-- AQUI EL WHILE -->
                        <?php foreach($this->cursos as $curso): ?>
                        <tr>
                            <td><?php echo $curso->codigo;?></td>
                            <td><?php echo $curso->curso;?></td>
                            <td>
                                <a href="<?= BASE_URL; ?>curso/editar/<?= $curso->codigo; ?>" title="Editar"><i class="icon-edit"></i></a>
                                <a href="#eliminar" title="Eliminar"><i class="icon-trash"></i></a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>


                <div class="pagination">
                    <ul>
                        <!-- AQUI EL CODIGO DE PAGINACION-->
                    </ul>
                </div>
            </div>
        </div>			
    </div>
</div>