<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>									
                </span>
                <h5><?= isset($this->titulo)?$this->titulo:''; ?></h5>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="<?= BASE_URL; ?>curso/grabar" name="form" id="form" novalidate="novalidate">
                    <div class="control-group">
                        <label class="control-label">Nombre del Curso</label>
                        <div class="controls">
                            <input type="text" name="curso" id="curso">
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="submit" value="Grabar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>